#  vim: set et fenc=utf-8 ff=unix sts=2 sw=2 ts=2 :
---
all:
  children:
    #------------------------------------------------------------------------#
    localhost:
      hosts:
        localhost:
          ansible_python_interpreter: /usr/bin/python
      vars:
        ansible_connection: local
    #------------------------------------------------------------------------#
    servers:
      hosts:
        server01:
          ansible_host: "{{ lookup('env', 'SSH_HOSTS').split(',')[0] }}"
    #------------------------------------------------------------------------#

  vars:
    ansible_user: "{{ lookup('env', 'SSH_USER') }}"
    ansible_port: "{{ lookup('env', 'SSH_PORT') }}"
    ansible_ssh_private_key_file: "{{ lookup('env', 'SSH_PATH') }}/{{ lookup('env', 'SSH_KEY') }}"
    ########################   COMMON  #####################################
    deployment_instance_id: "{{ inventory_dir | basename }}001"
    #deployment_email: admin@localhost
    ########################################################################
    generator__path: "{{ inventory_dir }}/.generated"
    ########################################################################
