#  vim: set et fenc=utf-8 ff=unix sts=2 sw=2 ts=2 :
---
- hosts: localhost
  gather_facts: False
  tasks:
    - include_vars: "{{ item }}"
      with_first_found:
        - files:
          - "secrets/{{ deployment_instance_id }}.yml"
          - "{{ inventory_dir }}/.secrets/{{ deployment_instance_id }}.yml"
          skip: true

- name: Install python to servers
  hosts: servers
  become: true
  gather_facts: no
  tasks:
    - raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- hosts: localhost
  roles:
    - generator

- hosts: servers
  roles:
    - basic
    - vpn
    - proxy
    #- vault
