#  vim: set et fenc=utf-8 ff=unix sts=2 sw=2 ts=2 :
---
all:
  children:
    #------------------------------------------------------------------------#
    localhost:
      hosts:
        localhost:
          #ansible_python_interpreter: /usr/bin/python
          ansible_python_interpreter: "{{ playbook_dir }}/.python/bin/python"
      vars:
        ansible_connection: local
    #------------------------------------------------------------------------#

    #------------------------------------------------------------------------#
    servers:
      hosts:
        server01:
          ansible_host: "{{ lookup('env', 'SSH_HOSTS').split(',')[0] }}"
    #------------------------------------------------------------------------#

  vars:
    ansible_user: "{{ lookup('env', 'SSH_USER') }}"
    ansible_port: "{{ lookup('env', 'SSH_PORT') }}"
    ansible_ssh_private_key_file: "{{ lookup('env', 'SSH_PATH') }}/{{ lookup('env', 'SSH_KEY') }}"
    ########################   COMMON  #####################################
    deployment_instance_id: "{{ inventory_dir | basename }}001"
    #deployment_email: admin@localhost
    ########################################################################
    generator__path: "{{ inventory_dir }}/.generated"
    ########################################################################
    yd__iid: "{{ lookup('env', 'APP_YANDEX_IID') }}"
    yd__passwd: "{{ lookup('env', 'APP_YANDEX_PASSWORD') }}"
    server_resources:
      server_name_suffix: server
      users:
        blinov:
          resources:
            entry_point__server_name: "blinov.server"
            entry_point_port: 4000
            ports:
              - "4000-4999"
        alex:
          resources:
            entry_point__server_name: "alex.server"
            entry_point_port: 5000
            ports:
              - "5000-5999"
